language: node_js
node_js:
  - '8'
before_script:
  - mkdir test-data
  - cd test-data
  - wget https://drive.voiceit.io/files/enrollmentBMyFaceAndVoice.m4a
  - wget https://drive.voiceit.io/files/enrollmentA1.wav
  - wget https://drive.voiceit.io/files/enrollmentA2.wav
  - wget https://drive.voiceit.io/files/enrollmentA3.wav
  - wget https://drive.voiceit.io/files/enrollmentA4.wav
  - wget https://drive.voiceit.io/files/verificationA1.wav
  - wget https://drive.voiceit.io/files/enrollmentC1.wav
  - wget https://drive.voiceit.io/files/enrollmentC2.wav
  - wget https://drive.voiceit.io/files/enrollmentC3.wav
  - wget https://drive.voiceit.io/files/videoEnrollmentB1.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentB2.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentB3.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentA1.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentA2.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentA3.mov
  - wget https://drive.voiceit.io/files/videoVerificationB1.mov
  - wget https://drive.voiceit.io/files/videoVerificationB2.mp4
  - wget https://drive.voiceit.io/files/videoEnrollmentC1.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentC2.mov
  - wget https://drive.voiceit.io/files/videoEnrollmentC3.mov
  - wget https://drive.voiceit.io/files/faceEnrollmentB1.mp4
  - wget https://drive.voiceit.io/files/faceEnrollmentB2.mp4
  - wget https://drive.voiceit.io/files/faceEnrollmentB3.mp4
  - wget https://drive.voiceit.io/files/faceEnrollmentA1.mov
  - wget https://drive.voiceit.io/files/faceEnrollmentA2.mov
  - wget https://drive.voiceit.io/files/faceEnrollmentA3.mov
  - wget https://drive.voiceit.io/files/faceVerificationB1.mp4
  - wget https://drive.voiceit.io/files/faceVerificationC1.mp4
  - cd ..
  - npm i
script:
  - npm test
notifications:
  slack:
    secure: rk/dzRcu62bvJcyXodbqFhoamjoZc96nxxiFj1hQhd7Z3ZXvVedata4/dR2Tg+WzwPz3YrB3YEGMr7oh0kJinYGYYl2hoPH3cuET+xORecFNcj3Li20oEFZCt1X3azJcnusTc0s/KOcoBSwo3rgX1b8QwahdDnTTuVkzXKhf93y2MQIbi7wvzdz0488elttWXqpUaKKQdjJ0VqOha1EPshzJyYqoMonmESnGA64v9eCXUWMuwAp390zOxY8/pQtCkX7Y9ovO3A2pgROUvxPT//071df+b9D1dz3rytoUQIoDmTkUY4Zn9d+RTFpiG18nf0O2pW4T375dcBlN2v0gi3zhd1odFLt1Q269mbRVJH8PChFAzwok7OhSS5kf6JdC0riNHLn7qDVkM1vNUv21P64d6jtEVO7TmxOeZD2c8M4IPJ7AhtB/3Uq1cFPk5ZTcaOEYbpnCCEKOv1KtJPS1NC+qY4vKX6IjnyXRP0Qidlz9poFa0j3tgRFbMPI8xgrd3KWwHgFc8xVfdQoymf/Dy7P5mY2+r3rt0hKrBR4bPcN8S6O5QocbtyBiA9Kcmiv6wDP62PEEsuQTlWG3d2+7TfOVdHYppeFN/h7pWbMyK2nDNMHXh4c64lQVsYWDatjYtD3T4txAESzZ3OVP83IV+ZxiomtMbLRAS8apM2wKVyE=
  email:
    on_success: never
    on_failure: never
after_success:
  - ./release.sh
deploy:
  skip_cleanup: true
  provider: npm
  email: B@voiceit.io
  api_key:
    secure: Kadq49lnbjEmJWIwWj9QloOL7h7DalnJiCJv0ea3KEAO1lzCVZ02JRZiD54P187EdtYRoYq+2CbVhEUaly5h5zHVbWvqLG1FPfKFCBlFZl2VWv5vQdIFm/QiO5oN6zTfw4f0AbXq9+VEaqB7jd/8Ss+HD3v9y3qRgGzjZiJGHXmYihlTqRvIiX/6n0tbvoDKp+ZACpg86dPFXR22y275tVINcd337DtSFXvmjd8eDO9mR8Fvd1CJjUCnSVYe48mgBWqCe/jTuEpNwVxlhY1vgUFh3u949BIB4NSBvthWFLrNDtzGdiClwvi9rkGCEwg9yIV1g20q3vcsuLzbcuVFjvP/fYcGzx0UyO4gA4BoQEJiGY7IW5PVNcJgzzNJL1OJAX3imemn0PC548/BENXiYEyxb/WZ1FqD7yUlEnY6KbyJiqlFAsnkKW9OtUecKneK1rBh8+G7/QGlyiUFcm7VG24SFwCEZiYuSDwBnTyGlDoeTN+dPuFeb07aE/YT7QH6QrtyAbLTcRAHJk22Sbo55Q4Z5LF3K42kD/BqSWQEod02g0NKV7fJqp0LoRvFRMM/8YO66FdIXO9DvdoorflEN9r45UJwC8flPp2GgrbbKEVE1RewCMdiMTe3e8xf11+KkyOT4/ch4LzyqmAWH5aBNFY9EHTGMNZBgVWJB73P7DE=
  on:
    branch: master
    condition: $DO_DEPLOY = YES
