const TestConfig = {
  CONTENT_LANGUAGE_REAL : 'en-US',
  CONTENT_LANGUAGE_FAKE : 'asdasd',
  FAKE_USER_ID: 'usr_asdsadsadsa',
  FAKE_GROUP_ID: 'grp_asdsadsadsa',
  INVALID_FILE_PATH: 'invalidFileFound',
  S3_FILES_URL:'https://s3.amazonaws.com/voiceit-api2-testing-files/',
  ENROLLMENT_FILE_FACE_AND_VOICE: 'test-data/enrollmentArmaanMyFaceAndVoice.m4a',
  ENROLLMENT_FILE_NOEL_1 : 'test-data/enrollmentNoel1.wav',
  ENROLLMENT_FILE_NOEL_2 : 'test-data/enrollmentNoel2.wav',
  ENROLLMENT_FILE_NOEL_3 : 'test-data/enrollmentNoel3.wav',
  VERIFICATION_FILE_NOEL_1 : 'test-data/verificationNoel1.wav',
  ENROLLMENT_FILE_STEPHEN_1 : 'test-data/enrollmentStephen1.wav',
  ENROLLMENT_FILE_STEPHEN_2 : 'test-data/enrollmentStephen2.wav',
  ENROLLMENT_FILE_STEPHEN_3 : 'test-data/enrollmentStephen3.wav',
  VIDEO_ENROLLMENT_FILE_ARMAAN_1 : 'test-data/videoEnrollmentArmaan1.mov',
  VIDEO_ENROLLMENT_FILE_ARMAAN_2 : 'test-data/videoEnrollmentArmaan2.mov',
  VIDEO_ENROLLMENT_FILE_ARMAAN_3 : 'test-data/videoEnrollmentArmaan3.mov',
  VIDEO_ENROLLMENT_FILE_NOEL_1 : 'test-data/videoEnrollmentNoel1.mov',
  VIDEO_ENROLLMENT_FILE_NOEL_2 : 'test-data/videoEnrollmentNoel2.mov',
  VIDEO_ENROLLMENT_FILE_NOEL_3 : 'test-data/videoEnrollmentNoel3.mov',
  VIDEO_VERIFICATION_FILE_ARMAAN_1 : 'test-data/videoVerificationArmaan1.mov',
  VIDEO_VERIFICATION_FILE_NOEL_1 : 'test-data/videoVerificationNoel1.mov',
  VIDEO_ENROLLMENT_FILE_STEPHEN_1 : 'test-data/videoEnrollmentStephen1.mov',
  VIDEO_ENROLLMENT_FILE_STEPHEN_2 : 'test-data/videoEnrollmentStephen2.mov',
  VIDEO_ENROLLMENT_FILE_STEPHEN_3 : 'test-data/videoEnrollmentStephen3.mov',
  FACE_ENROLLMENT_FILE_ARMAAN_1 : 'test-data/faceEnrollmentArmaan1.mp4',
  FACE_ENROLLMENT_FILE_ARMAAN_2 : 'test-data/faceEnrollmentArmaan2.mp4',
  FACE_ENROLLMENT_FILE_ARMAAN_3 : 'test-data/faceEnrollmentArmaan3.mp4',
  FACE_ENROLLMENT_FILE_NOEL_1 : 'test-data/faceEnrollmentNoel1.mov',
  FACE_ENROLLMENT_FILE_NOEL_2 : 'test-data/faceEnrollmentNoel2.mov',
  FACE_ENROLLMENT_FILE_NOEL_3 : 'test-data/faceEnrollmentNoel3.mov',
  FACE_VERIFICATION_FILE_ARMAAN_1 : 'test-data/faceVerificationArmaan1.mp4',
  FACE_VERIFICATION_FILE_STEPHEN_1 : 'test-data/faceVerificationStephen1.mp4',
  ENGLISH_PHRASE : 'Never forget tomorrow is a new day',
  getURL:(filePath)=>{
    return `${TestConfig.S3_FILES_URL}${filePath}`;
  }
}
module.exports = TestConfig;
