const TestConfig = {
  CONTENT_LANGUAGE_REAL : 'en-US',
  CONTENT_LANGUAGE_FAKE : 'asdasd',
  FAKE_USER_ID: 'usr_asdsadsadsa',
  FAKE_GROUP_ID: 'grp_asdsadsadsa',
  INVALID_FILE_PATH: 'invalidFileFound',
  S3_FILES_URL:'https://drive.voiceit.io/files/',
  ENROLLMENT_FILE_FACE_AND_VOICE: 'test-data/enrollmentBMyFaceAndVoice.m4a',
  ENROLLMENT_FILE_A_1 : 'test-data/enrollmentA1.wav',
  ENROLLMENT_FILE_A_2 : 'test-data/enrollmentA2.wav',
  ENROLLMENT_FILE_A_3 : 'test-data/enrollmentA3.wav',
  VERIFICATION_FILE_A_1 : 'test-data/verificationA1.wav',
  VERIFICATION_FILE_A_2 : 'test-data/enrollmentA4.wav',
  ENROLLMENT_FILE_C_1 : 'test-data/enrollmentC1.wav',
  ENROLLMENT_FILE_C_2 : 'test-data/enrollmentC2.wav',
  ENROLLMENT_FILE_C_3 : 'test-data/enrollmentC3.wav',
  VIDEO_ENROLLMENT_FILE_B_1 : 'test-data/videoEnrollmentB1.mov',
  VIDEO_ENROLLMENT_FILE_B_2 : 'test-data/videoEnrollmentB2.mov',
  VIDEO_ENROLLMENT_FILE_B_3 : 'test-data/videoEnrollmentB3.mov',
  VIDEO_ENROLLMENT_FILE_A_1 : 'test-data/videoEnrollmentA1.mov',
  VIDEO_ENROLLMENT_FILE_A_2 : 'test-data/videoEnrollmentA2.mov',
  VIDEO_ENROLLMENT_FILE_A_3 : 'test-data/videoEnrollmentA3.mov',
  VIDEO_VERIFICATION_FILE_B_1 : 'test-data/videoVerificationB1.mov',
  VIDEO_VERIFICATION_FILE_B_2 : 'test-data/videoVerificationB2.mp4',
  VIDEO_VERIFICATION_FILE_A_1 : 'test-data/videoVerificationA1.mov',
  VIDEO_ENROLLMENT_FILE_C_1 : 'test-data/videoEnrollmentC1.mov',
  VIDEO_ENROLLMENT_FILE_C_2 : 'test-data/videoEnrollmentC2.mov',
  VIDEO_ENROLLMENT_FILE_C_3 : 'test-data/videoEnrollmentC3.mov',
  FACE_ENROLLMENT_FILE_B_1 : 'test-data/faceEnrollmentB1.mp4',
  FACE_ENROLLMENT_FILE_B_2 : 'test-data/faceEnrollmentB2.mp4',
  FACE_ENROLLMENT_FILE_B_3 : 'test-data/faceEnrollmentB3.mp4',
  FACE_ENROLLMENT_FILE_A_1 : 'test-data/faceEnrollmentA1.mov',
  FACE_ENROLLMENT_FILE_A_2 : 'test-data/faceEnrollmentA2.mov',
  FACE_ENROLLMENT_FILE_A_3 : 'test-data/faceEnrollmentA3.mov',
  FACE_VERIFICATION_FILE_B_1 : 'test-data/faceVerificationB1.mp4',
  FACE_VERIFICATION_FILE_C_1 : 'test-data/faceVerificationC1.mp4',
  ENGLISH_PHRASE : 'Never forget tomorrow is a new day',
  getURL:(filePath)=>{
    return `${TestConfig.S3_FILES_URL}${filePath.replace('test-data/', '')}`;
  }
}
module.exports = TestConfig;
